### ISSUE TITLE
format_dict SyntaxError

### ISSUE THREAD

**Issue by cometsong** [maverickwoo/vcprompt#9]
`python -V`:
Python 2.6.6
The default python version on most unix boxes I work on is the pre-installed v2.6.6.

`vcprompt -f '%s:%b'`:
File "/home1/microbi9/bin/vcprompt", line 205
    format_dict = {'%{}'.format(fmt[:1]): '{:%ss}' % get_group(fmt[1:]) for fmt in format_strings}

With `python -v` == "Python 2.7.10" or above (v3.x) there is no error given.

This error also happens when I have `VCPROMPT_FORMAT` set to `-(%s:%b:%m%u%a)`

Thoughts to repair/workaround?

**Comment by maverickwoo** [comment]
May I suggest that you try to change that line into a 2.6-compatible syntax (see URL below)? And if it works, would you please submit a pull request?

http://stackoverflow.com/questions/21069668/alternative-to-dict-comprehension-prior-to-python-2-7

Thanks!

**Comment by cometsong** [comment]
@maverickwoo FYI:  Good call.  This `format_dict` mod is now in progress.  :)

**Comment by cometsong** [comment]
Closing... partly for ancient age, partly because I've stopped using Python 2._anything_ anyway. 😄
